name: Deploy ECS instance

on:
  workflow_call:
    inputs:
      aws_region:
        description: "AWS region to deploy"
        required: true
        type: string
      company:
        description: "Company name"
        required: false
        type: string
        default: "dieselbank"
      projects_directory:
        description: "Directory to find services"
        required: true
        type: string
      environment:
        description: "Environment to deploy to"
        required: true
        type: string
      await_deploy:
        description: "Waits for deploy stability"
        required: false
        type: boolean
        default: false
    secrets:
      ACCESS_TOKEN:
        required: true
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      AWS_SESSION_TOKEN:
        required: false

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      project_name: ${{ steps.variables.outputs.PROJECT }}
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          submodules: 'recursive'

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ inputs.aws_region }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Set environmental variables
        id: variables
        run: |
          TAG=${GITHUB_REF/refs\/tags\//}
          PROJECT=${TAG/@**/}
          echo "PROJECT=${TAG/@**/}" >> $GITHUB_ENV
          echo "PROJECT=${TAG/@**/}" >> $GITHUB_OUTPUT
          echo "VERSION=${TAG/**@/}" >> $GITHUB_ENV
          echo "IMAGE=${{ steps.login-ecr.outputs.registry }}/${{ inputs.company }}/${{ inputs.environment }}/${TAG/@/:}" >> $GITHUB_ENV

      - name: Docker [build image]
        run: > 
          docker compose 
          --env-file=${{ inputs.projects_directory }}/${{ env.PROJECT }}/.env 
          build 
          --build-arg=ENV=${{ inputs.environment }} 
          --build-arg=PROJECT=${{ env.PROJECT }}
          ${{ env.PROJECT }}

      - name: Docker [Push image to Amazon ECR]
        run: docker push ${{ env.IMAGE }}

      # UPDATE TASKS
      - name: Fills Task definition with ECR image ID
        id: task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: ${{ inputs.projects_directory }}/${{ env.PROJECT }}/task-definition.${{ inputs.environment }}.json
          container-name: ${{ env.PROJECT }}
          image: ${{ env.IMAGE }}

      - name: Rename Task definition
        run: mv ${{ steps.task-def.outputs.task-definition }} task-definition.json

      - name: Upload artifact [task definition]
        uses: actions/upload-artifact@v3
        with:
          name: task-definition
          path: task-definition.json

  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    needs: [ build ]
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: Download artifact [task definition]
        uses: actions/download-artifact@v3
        with:
          name: task-definition
      - name: Deploy Amazon ECS task definition
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: task-definition.json
          service: service-${{ inputs.environment }}-${{ needs.build.outputs.project_name }}
          cluster: ${{ inputs.environment }}-${{ needs.build.outputs.project_name }}
          wait-for-service-stability: ${{ inputs.await_deploy }}

